package com.tala.origindata.domain;

import com.tala.core.domain.BaseEntity;
import com.tala.origindata.constant.DataSourceType;
import com.tala.origindata.constant.TimelineEventType;
import io.hypersistence.utils.hibernate.type.json.JsonBinaryType;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.Type;

import java.time.Instant;

/**
 * Timeline Entry - AI-generated display data
 * 
 * Represents a single displayable event in the baby's timeline.
 * Generated by AI from original data sources.
 */
@Entity
@Table(name = "timeline_entries", schema = "origin_data", indexes = {
    @Index(name = "idx_timeline_entry_profile", columnList = "profile_id"),
    @Index(name = "idx_timeline_entry_type", columnList = "timeline_type"),
    @Index(name = "idx_timeline_entry_source", columnList = "data_source"),
    @Index(name = "idx_timeline_entry_time", columnList = "record_time"),
    @Index(name = "idx_timeline_entry_original", columnList = "original_event_id")
})
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class TimelineEntry extends BaseEntity {
    
    @Column(name = "original_event_id", nullable = false)
    private Long originalEventId;
    
    @Column(name = "profile_id", nullable = false)
    private Long profileId;
    
    @Enumerated(EnumType.STRING)
    @Column(name = "timeline_type", nullable = false, length = 50)
    private TimelineEventType timelineType;
    
    @Enumerated(EnumType.STRING)
    @Column(name = "data_source", nullable = false, length = 50)
    private DataSourceType dataSource;
    
    @Column(name = "record_time", nullable = false)
    private Instant recordTime;
    
    @Column(name = "title", length = 255)
    private String title;
    
    @Column(name = "ai_summary", columnDefinition = "TEXT")
    private String aiSummary;
    
    @Type(JsonBinaryType.class)
    @Column(name = "ai_tags", columnDefinition = "jsonb")
    private String aiTags;
    
    @Column(name = "location", length = 255)
    private String location;
    
    @Column(name = "ai_model_version", length = 50)
    private String aiModelVersion;

    @Column(name = "original_user_message", columnDefinition = "TEXT")
    private String originalUserMessage;
}
